### ISSUE TITLE
Add back symbol in front of the "View the latest post" link

### ISSUE THREAD

**Issue by Dark1z** [primehalo/primepostrevisions#20]
https://github.com/primehalo/primepostrevisions/pull/19#issuecomment-648299977 : 
> I was thinking we should add `↩` in front of the "View the latest post" link, but to keep it safe with RTL languages we should add it via CSS ::before `content: "↩ ";` instead of putting it directly in the template.
> ![Clipboard01](https://user-images.githubusercontent.com/86633/85434326-b7868b00-b53a-11ea-9bb9-989471a05f9c.png)

What about : 
Unicode Emoji : 
- `🔙`
- `📄`

Font Awesome : 
- https://fontawesome.com/v4.7.0/icon/arrow-left
- https://fontawesome.com/v4.7.0/icon/arrow-circle-o-left
- https://fontawesome.com/v4.7.0/icon/chevron-circle-left
- https://fontawesome.com/v4.7.0/icon/arrow-circle-left

I prefer **Font Awesome** .

Best regards 👍

**Comment by Dark1z** [comment]
My proposal :

Before : 
![1](https://user-images.githubusercontent.com/25451052/85446373-fd326a80-b5b1-11ea-9d45-84e855d7181b.png)

After : 
![2](https://user-images.githubusercontent.com/25451052/85446393-04597880-b5b2-11ea-9f9b-71aef6660ada.PNG)

This is using **Font Awesome** , the phpBB Responsive design handles the RTL/LTR languages automatically.

Should I do the PR ???

Best regards 👍

**Comment by primehalo** [comment]
So the arrow will point the correct direction when using Arabic? If it works, I'm okay with it. I'd also like to try `content: '\2039';` in place of « just to see how it looks. That's what phpBB uses to separate their breadcrumbs. It _might_ look nice if it was consistent with the breadcrumbs. Actually, do you know how to set breadcrumbs in phpBB? I'm noticing there are no breadcrumbs on the revision history page so that might be cool to set up if it's not too difficult.

**Comment by primehalo** [comment]
I figured out how to add breadcrumbs so I added them to the post history page. I wasn't sure if I should label the right most breadcrumb the "Current post" or the subject of the post. I thought "Current post: [post subject]" looked a little too crowded.

**Comment by Dark1z** [comment]
I was supposed to suggest you to move this to Breadcrumbs, but you already beat me to it.
I made some fixes for the same in commit : https://github.com/primehalo/primepostrevisions/commit/66051a8040e778a82fc864d015c6fedc77b3a462
Kindly check.

Fixed : 
- Breadcrumbs should have current page , always.
- Breadcrumb for Topic was missing.

Best regards 👍

**Comment by Dark1z** [comment]
Now that we have Breadcrumbs , do we really need this : 
![](https://user-images.githubusercontent.com/25451052/85446393-04597880-b5b2-11ea-9f9b-71aef6660ada.PNG)
like : `← View the latest post  « View post history`

I think , it's better to remove that. What do you think ?

Best regards 👍

**Comment by primehalo** [comment]
I kind of do want to still keep those as I think it might help people. I don't know about other people but I'm not always looking at breadcrumbs.

**Comment by Dark1z** [comment]
Ok. Then I'll do the required changes you wanted.
