### ISSUE TITLE
Add a message "This page shows all versions..." text.

### ISSUE THREAD

**Issue by Dark1z** [primehalo/primepostrevisions#21]
https://github.com/primehalo/primepostrevisions/pull/19#issuecomment-648299977 : 
> Do you think we should add a message after the "_**This page shows all versions...**_" text that tells how many total edits and how many revisions there are? Something like "_**Edited 4 times in total. Showing 2 saved revision.**_", "_**Total Edits: 4, Saved Revisions: 2**_", or "_**Saved revisions: 2 out of 4 total edits**_"?

To Be Honest , I am against it.
This will simply increase the complexity of the extensions.

But if you really want to add this , then it's not a problem for me, you can do so as you please.
Do remember we are also pruning the previous revisions via cron, so there will always be some revisions deleted if enabled.

Best regards 👍

**Comment by primehalo** [comment]
It was just a thought, nobody has actually requested it so I'm fine with leaving it out.
