### ISSUE TITLE
Extension enable failed

### ISSUE THREAD

**Issue by rokx** [primehalo/primepostrevisions#27]
Downloaded 1.0.2 and placed in ext folder.

After trying to activate the extension via ACP I get the following error:

[Tue Sep 07 09:17:37.813742 2021] [php7:error] [pid 149] [client 172.29.0.1:32846] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to phpbb\\db\\migrator::get_callable_from_step() must be of the type array, string given, called in /opt/bitnami/phpbb/phpbb/db/migrator.php on line 704 and defined in /opt/bitnami/phpbb/phpbb/db/migrator.php:726\nStack trace:\n#0 /opt/bitnami/phpbb/phpbb/db/migrator.php(704): phpbb\\db\\migrator->get_callable_from_step('config.add', 0, false)\n#1 /opt/bitnami/phpbb/phpbb/db/migrator.php(661): phpbb\\db\\migrator->run_step('config.add', 0, false)\n#2 /opt/bitnami/phpbb/phpbb/db/migrator.php(436): phpbb\\db\\migrator->process_data_step(Array, false)\n#3 /opt/bitnami/phpbb/phpbb/db/migrator.php(288): phpbb\\db\\migrator->try_apply('\\\\primehalo\\\\prim...')\n#4 /opt/bitnami/phpbb/phpbb/db/migrator.php(241): phpbb\\db\\migrator->update_do()\n#5 /opt/bitnami/phpbb/phpbb/extension/base.php(78): phpbb\\db\\migrator->update()\n#6 /opt/bitnami/phpbb/phpbb/extension/manager.php(231): phpbb\\extension\\base->enable_step(true)\n#7 /opt/bitnami/phpbb/includes/acp/acp_extensions.php(209): phpbb\\extension\\manager in /opt/bitnami/phpbb/phpbb/db/migrator.php on line 726, referer: https://<masked>/forum/adm/index.php?i=acp_extensions&sid=bfa21a3714d9fb24221f59ed9c02af49&mode=main&action=enable_pre&ext_name=primehalo%2Fprimepostrevisions

[07/Sep/2021:09:17:37 +0000] "POST /adm/index.php?i=acp_extensions&sid=bfa21a3714d9fb24221f59ed9c02af49&mode=main&action=enable&ext_name=primehalo%2Fprimepostrevisions&hash=ae03522a HTTP/1.1" 500 -

Running phpBB version 3.3.4 on PHP version 7.3.28.

Any help appreciated.

**Comment by rokx** [comment]
Suspect it is connected to install_acp_module.php lines containing config.add that are not in array format.

`grep "config.add" *

install_acp_module.php:                 'config.add', ['primepostrev_enable_general'    => true],
install_acp_module.php:                 'config.add', ['primepostrev_enable_autoprune'  => true],
install_cron2.php:                      ['config.add', ['primepostrev_cron_last_run', 0, true]],
install_cron.php:                       ['config.add', ['primepostrev_cron_last_run', 0, true]],
`

**Comment by rokx** [comment]
Changed in install_acp_module.php from  
```
36                         'config.add', ['primepostrev_enable_general' => true],
37                          'config.add', ['primepostrev_enable_autoprune' => true],
```

to 
```
36                         ['config.add', ['primepostrev_enable_general', true]],
37                         ['config.add', ['primepostrev_enable_autoprune', true]],
```


Extension activated successfuly.

**Comment by Dark1z** [comment]
That's how it is anyway :
https://github.com/primehalo/primepostrevisions/blob/1520077cd67fad0a6c0e6bc859ef852215023e50/migrations/install_acp_module.php#L36-L37

**Comment by rokx** [comment]
I see now. But it is not in release 1.0.2. I downloaded the code there.
