### ISSUE TITLE
Post edit time is same for all revisions

### ISSUE THREAD

**Issue by bazcode** [primehalo/primepostrevisions#28]
Steps to reproduce:
- Post a new topic as user A
- Post a comment in the new topic as user A (lets say this is timestamp 1 for the comment post)
- Wait a minute or so
- Edit the comment in the new topic as user A (lets say this is timestamp 2 for the comment post)
- Check the history of the comment as an admin user
- I have three revisions, all with the same post timestamp 1, where I expect to see the timestamp that matches the revision (so first timestamp 1, then timestamp 2)

I managed to achieve this by editing controller/controller.php 
Line 302, from:
`$post_date		= empty($row['primepost_edit_time']) ? $post_data['post_time'] : $row['primepost_edit_time'];`
to this:
`$post_date		= empty($row['revision_time']) ? $post_data['post_time'] : $row['revision_time'];`

Is this expected behavior to see the same timestamp for all revisions?
We use the PPR extension to see when someone edited a post, so we need to see the timestamps when the post was edited/revision was created.

**Comment by Dark1z** [comment]
Fixed in https://github.com/primehalo/primepostrevisions/tree/Fix-Post-Edit-Time
